"""
Merge helpers for the aggregated multi-source query.

Each source (human, fly, custom) returns a graph in the unified
``{nodes: [{'data': ...}], edges: [{'data': ...}]}`` shape produced by
Result_Formatter. Nodes that share the same underlying id (e.g. a gene id)
are merged into a single node whose properties are the union of the source
properties.

Known limitation: cross-source merge only works when the Custom node label
matches the Human/Fly BioCypher label (e.g. both ``gene``). If an upload
names the entity differently (``Gene``), normalization rewrites the id
token but not the label, so the same gene will not merge.
"""


def is_empty_id(node_id):
    """Return True when a formatter-produced id carries no identifier.

    Result_Formatter always emits ``"{label} {value}"``; an empty or None
    ``id`` property becomes ``"gene "`` or ``"gene None"``. Treating those
    as missing prevents distinct nodes from collapsing onto one shared key.
    """
    if not node_id:
        return True
    value = node_id.split(" ", 1)[-1].strip()
    return not value or value.lower() == "none"


def merge_graphs(graphs, merge_key='id'):
    """Merge a list of unified graphs by the given node key.

    Args:
        graphs: iterable of ``{'nodes': [...], 'edges': [...]}``.
        merge_key: node data field used to detect shared nodes. Defaults to
            ``id`` which is how Result_Formatter exposes gene ids.

    Returns:
        A single unified graph with deduplicated nodes/edges.
    """
    merged_nodes = {}
    node_order = []
    merged_edges = {}
    edge_order = []

    for graph in graphs:
        for node in graph.get('nodes', []):
            data = node.get('data', {})
            key = data.get(merge_key)
            if not key or is_empty_id(key):
                key = ('raw', id(data))
            if key not in merged_nodes:
                merged_nodes[key] = dict(data)
                node_order.append(key)
            else:
                merged_nodes[key].update(data)

        for edge in graph.get('edges', []):
            data = edge.get('data', {})
            source = data.get('source')
            label = data.get('label')
            target = data.get('target')
            if not label or is_empty_id(source) or is_empty_id(target):
                edge_key = ('raw', id(data))
            else:
                edge_key = (source, label, target)
            if edge_key not in merged_edges:
                merged_edges[edge_key] = dict(data)
                edge_order.append(edge_key)

    return {
        "nodes": [{"data": merged_nodes[key]} for key in node_order],
        "edges": [{"data": merged_edges[key]} for key in edge_order],
    }


def build_custom_request(requests):
    """Return a deep copy of the request whose node ids use the Custom form.

    Custom nodes store their id as ``"{label}_{pk}"`` (the lowercased,
    underscored HugeGraph composite id produced by ``preprocessId``), e.g.
    ``gene_ensg00000139618``. ``preprocessId`` lowercases the id and replaces
    spaces/colons with underscores, so a disease id ``DOID:123`` is stored as
    ``disease_doid_123``. The MATCH clause generated by ``query_Generator``
    must therefore use that exact form, not the bare biological id, or the
    Custom source will never match a node. The caller passes the transformed
    copy only to the Custom-source query generator.
    """
    import copy

    custom_requests = copy.deepcopy(requests)
    for node in custom_requests["nodes"]:
        node_id = node.get("id")
        if node_id:
            preprocessed = node_id.lower().replace(" ", "_").replace(":", "_")
            node["id"] = f"{node['type']}_{preprocessed}"
    custom_node_map = {
        node["node_id"]: node for node in custom_requests["nodes"]
    }
    return custom_requests, custom_node_map


def normalize_custom_node_id(node_data):
    """Turn a Custom formatter node id back into the Human/Fly style.

    Custom nodes store their id as ``{label} {label}_{biological_id}``
    (e.g. ``gene gene_ensg00000139618``) because the HugeGraph composite id
    is lowercased/underscored by ``preprocessId``. Human/Fly nodes use the
    plain biological id (e.g. ``gene ENSG00000139618``).

    This normalizes the Custom form so both sides can be merged on the same
    ``data['id']`` value. If the id does not match the expected shape the
    node is returned unchanged.
    """
    node_id = node_data.get("id")
    if not node_id:
        return node_data

    parts = node_id.split(" ", 1)
    if len(parts) != 2:
        return node_data

    node_label, raw_id = parts
    prefix = f"{node_label}_".lower()
    if raw_id.lower().startswith(prefix):
        biological_id = raw_id[len(prefix):]
        if biological_id.lower().startswith(("ensg", "ensm")):
            biological_id = biological_id.upper()
        elif biological_id.lower().startswith("fbgn"):
            biological_id = "FBgn" + biological_id[4:]
        node_data = dict(node_data)
        node_data["id"] = f"{node_label} {biological_id}"
    return node_data


def normalize_custom_graph(graph):
    """Normalize every node/edge id in a Custom graph to the Human/Fly style.

    Edge ``source``/``target`` values are built from the same
    ``{label} {id}`` pattern by the formatter, so they are normalized with
    the same helper (the label is recovered from the id prefix).
    """
    nodes = []
    for node in graph.get('nodes', []):
        nodes.append({"data": normalize_custom_node_id(dict(node.get('data', {})))})

    edges = []
    for edge in graph.get('edges', []):
        data = dict(edge.get('data', {}))
        data['source'] = normalize_custom_node_id(
            {'id': data.get('source')}).get('id', data.get('source'))
        data['target'] = normalize_custom_node_id(
            {'id': data.get('target')}).get('id', data.get('target'))
        edges.append({"data": data})

    return {"nodes": nodes, "edges": edges}