services:
  annotation_service:
    image: "${DOCKER_HUB_REPO}"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "${APP_PORT}:8000"
    command: gunicorn -w 16 --bind 0.0.0.0:${APP_PORT} run:app
    restart: always
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=${MONGO_URI}

  mongodb:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "${MONGODB_DOCKER_PORT}:27017"
    restart: always

  caddy:
    image: caddy:latest
    ports:
      - "${CADDY_PORT}:${CADDY_PORT_FORWARD}"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    command: caddy reverse-proxy --from http://localhost:${CADDY_PORT} --to http://annotation_service:${APP_PORT}
    restart: always
    depends_on:
      - annotation_service

volumes:
  mongo_data:
  caddy_data:
  caddy_config:
