elasticsearch:
  host: "https://localhost:9200" # Update this with your Elasticsearch host
  index:
    name: "nodes"
    settings:
      number_of_shards: 1
      number_of_replicas: 1
    mappings:
      properties:
        name:
          type: text
        name.suggest:
          type: completion
          analyzer: simple
          preserve_separators: true
          preserve_position_increments: true
          max_input_length: 50
          contexts:
            label:
              type: category
        labels:
          type: keyword
        name_field:
          type: keyword
