name: Run Tests Before Merge

# Trigger workflow on push or pull request to the main branch
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python (if using Python)
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust based on your project setup

    - name: Run Tests
      run: |
        pytest  # or any other test command for your framework

    - name: Notify on test failure (optional)
      if: failure()
      run: echo "Tests failed! Fix issues before merging."

